#!/bin/sh
set -e

if [ $# -eq 0 ]; then 
	sleep 5
	# mysql Command
	mycli="mysql -uroot -P$MRBS_DB_PORT -h$MRBS_DB_HOST -p$MYSQL_ROOT_PASSWORD"
	# Check if DB exists:
	dbexists=0
	mysqlshow -u root \
	          -P$MRBS_DB_PORT \
		  -h$MRBS_DB_HOST \
		  -p$MYSQL_ROOT_PASSWORD | \
		  sed '1,/Databases/d' | \
		  awk '{print $2}' | grep $MRBS_DB_NAME > /dev/null 2>&1 && dbexists=1


	if [ $dbexists -eq 0 ]; then 
	  echo "Database $MRBS_DB_NAME does not exist."
	  echo "Creating and initializing." 
       	  $mycli -e "CREATE DATABASE ${MRBS_DB_NAME};"
	  $mycli -e "CREATE USER IF NOT EXISTS ${MRBS_DB_USER}@'%' IDENTIFIED BY '${MRBS_DB_PASSWORD}';"
	  $mycli -e "ALTER USER IF EXISTS ${MRBS_DB_USER}@'%' IDENTIFIED BY '${MRBS_DB_PASSWORD}';"
	  $mycli -e "GRANT ALL PRIVILEGES ON ${MRBS_DB_NAME}.* TO ${MRBS_DB_USER}@'%';"
	  $mycli -e "FLUSH PRIVILEGES;"
 	 else
	  echo "Database $MRBS_DB_NAME exists."
	  echo "Doing nothing."
  	fi

	apache2-foreground
else
	exec "$@"
fi

